김수연 과제제출
GDSC-SKHU/GDSC-Server-Assignment-04 pull request #3
Opened 2022-11-21 10:21 UTC by tndusy27

## Description

> 프로젝트의 전체적인 구성을 적어주세요. 예) ~하는 사이트이며 ~하는 기능이 있다. 

상품 관리하는 사이트이며
맨 처음 로그인, 회원가입 기능이 있고
회원가입하고 로그인을 해야만 상품 관리 페이지로 넘어갈 수 있다. 
상품 관리 기능으로는  상품 목록 보기, 상품 상세 정보, 상품 등록, 상품 수정, 상품 삭제 기능이 있다.
로그아웃 기능도 넣어 로그아웃을 하면 맨 처음 페이지로 이동할 수 있게 구현했다. 

 - 회원가입시 아이디와 비밀번호 2~8자 사이로 지정하게끔 설정
 - 회원가입하고 로그인을 하면 상품 목록 페이지로 이동
 - Item은 id(아이디), itemName(상품명), price(가격), quantity(수량)으로 구성
 - 상품 등록 페이지에서 상품명, 가격, 수량을 사용자가 직접 입력할 수 있게 구성
 - 상품 등록하면 등록한 정보가 맞는지 상품 상세페이지로 이동 상품 정보가 맞지 않다면 상품 수정 가능
 - 잘못 등록했을 시 상품 삭제 가능
 - 상품 등록을 하면 그동안 등록한 상품 정보를 볼 수 있는 상품 목록보기 페이지로 이동 가능
 - 로그아웃 하면 로그인 회원가입 페이지로 이동

home : 로그인, 회원가입 페이지
signin : 로그인 페이지
signup : 회원가입 페이지
addForm : 상품 등록 페이지
editForm : 상품 수정 페이지
Item : 상품 상세 정보 페이지
Items : 상품 목록 페이지

## Question

> 해당 웹 서비스를 만들면서 어려웠거나, 고민했거나, 궁금한 점이 있다면 적어주세요
- !
- 

## Reference

백엔드 블로그

2022-11-21 13:15 UTC, vact19 approved these changes
스터디 시간에 Map의 Value 변경에 대해 이야기했는데, 
Map이 제공하는 put이나 replace 메소드를 사용하는 방법도 있지만
참조값을 가져와서 변경하는 방식은 생각 못했네요! 👍👍

2022-11-22 13:11 UTC, hangillee requested changes
.idea 디렉토리를 제외하고 커밋해주세요!

2022-11-22 14:07 UTC, vact19 approved these changes
LGTV👍

2022-11-22 14:07 UTC, vact19 approved these changes
??

2022-11-22 14:11 UTC, hangillee approved these changes

2022-11-22 14:11 UTC, merged